services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DRAWIO_EXPORT_URL=http://drawio-export:8000
    depends_on:
      drawio-export:
        condition: service_started

  drawio-export:
    image: jgraph/export-server
    ports:
      - "9000:8000"
    restart: unless-stopped
